package com.x10.photo.maker

object PreferencesKey {
    const val COUNTRY_CODE = "COUNTRY_CODE"
    const val URL_WALLPAPER_LIVE_IF_PREVIEW = "URL_WALLPAPER_LIVE_IF_PREVIEW"
    const val URL_WALLPAPER_LIVE_IF_SET = "URL_WALLPAPER_LIVE_IF_SET"
    const val IS_FIRST_TIME_OPEN_APP = "IS_FIRST_TIME_OPEN_APP"
    const val IS_CALL_API_TRACKING_INSTALLATION = "IS_CALL_API_TRACKING_INSTALLATION"
    const val TIME_GENERATE_VIDEO_PREVIEW = "TIME_GENERATE_VIDEO_PREVIEW"
}