package com.x10.photo.maker.enums

enum class SegmentType(val type: String) {
    FIT_CENTER_SEGMENT(type = "FIT_CENTER_SEGMENT"),
    MOVE_TRANSITION_HORIZONTAL_SEGMENT(type = "MOVE_TRANSITION_HORIZONTAL_SEGMENT"),
    MOVE_TRANSITION_VERTICAL_SEGMENT(type = "MOVE_TRANSITION_VERTICAL_SEGMENT"),
    SINGLE_BITMAP_SEGMENT(type = "SINGLE_BITMAP_SEGMENT"),
    WINDOW_SEGMENT(type = "WINDOW_SEGMENT"),
    SCALE_TRANS_SEGMENT(type = "SCALE_TRANS_SEGMENT"),
    FIT_CENTER_SCALE_SEGMENT(type = "FIT_CENTER_SCALE_SEGMENT"),
    GRADIENT_TRANSFER_SEGMENT(type = "GRADIENT_TRANSFER_SEGMENT"),
    SCALE_SEGMENT(type = "SCALE_SEGMENT"),
    THAW_SEGMENT(type = "THAW_SEGMENT");

}